### ISSUE TITLE
Can't run/build pedsnet-dqa from source

### ISSUE THREAD

**Issue by eceowl** [PEDSnet/tools#105]
A few issues are making it impossible to run the pedsnet-dqa tool from the current master branch.  These are as follows:

- A few imports were still referring to the `dqa-pedsnet` repository which was deleted and is now stored within this (`tools`) repository.

- The go-github client api now requires a `context.Context` object passed to each function call made.

**Comment by writetoritu** [comment]
@bruth please help!

**Comment by eceowl** [comment]
@writetoritu O I have a PR, just forgot to make the issue first.

**Comment by eceowl** [comment]
PR here: #106
