### ISSUE TITLE
Extend dqa-files tool to produce markdown-based issue

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#16]
The input data would be a filled out CSV file ([example](https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Nemours/ETLv4/drug_exposure.csv)) and produces the Markdown to render the body of a DQA results GitHub issue ([example](https://github.com/PEDSnet/Nemours/issues/12)).

The structure of the Markdown file is:
- Top-level message
- h1. per rank (High, Medium, Low)
- h2. Group by table
- Order list of fields with issues

Each field issue is structured:

```
1. **<field_name>**: <issue_description> (<finding>)
```

/cc @writetoritu @utidjianl @aaron0browne

**Comment by bruth** [comment]
The template would look like:

``` go
{{.Message}}
{{range .Ranks}}# {{.Label}}
{{range .Tables}}## {{.Label}}
{{range .Fields}}{{range .Results}}{{if .IssueCode}}[ ] 1. **{{.Name}}**: {{.IssueDescription}} {{if .Finding}}({{.Finding}}){{end}}{{end}}
{{end}}
{{end}}
{{end}}
```

**Edit**: there can be multiple results per field, one for each goal.

**Comment by bruth** [comment]
Example output

---

# High

## drug_exposure

1. **days_supply**: Missing Information (100%)
1. **dose_unit_concept_id**: Missing Information (Why is there no information even though the effective drug dose seems  to be  available at Nemours)
1. **dose_unit_source_value**: Unexpected Facts (Are these values extracted directly from EHR (i.e. untransformed). In other words, were the units already computed by dose in the EHR?)
1. **drug_source_value**: Most frequent values significantly different from other sites (the top source codes correspond to ingredients (as opposed to more granular level of drugs that we see at other sites), e.g. 435 (albuterol), 723(amoxicillin). Does that mean that in the source EHR, no dose form or strength of drug was recorded)
1. **route_concept_id**: Concept distribution graph inconsistent with source values (please refer to the conventions document)

## fact_relationship

1. **domain_concept_id_1**: unexpected difference from previous ETL run (the number of recods in this table reduced by a factor of 10)
1. **relationship_concept_id**: Other (the relationship type linking related visits (e.g. ED turned into inpatient) are missing)

## observation

1. **observation_concept_id**: Unexpected Distributions (there are 25M admission form, discharge detail, and discharge to establishment observations in the table. However there are only 24M visits in all. And such observations should only be recorded for inpatient visits (that are 1M inpatient visits in the dataset))1. **observation_concept_id**: Other (we don�t see any chart availability or biobank specimen and there are barely any DRGs)

## procedure_occurrence

1. **procedure_occurrence_id**: unexpected difference from previous ETL run (decreased from 8M to 3M)

## visit_payer

1. **plan_class**: Unexpected Facts (please see conventions document on how to populate this)
1. **plan_type**: Unexpected Facts (please see conventions document on how to populate this)


# Medium

## condition_occurrence

1. **condition_end_date**: Unexpected difference from previous ETL run (lower end was 1997 and now its 1979)
1. **condition_start_date**: Unexpected difference from previous ETL run (lower end was 1869 and now its 1979)1. **condition_start_date**: Implausible Events (There are 73 records with condition_start_date>condition_end_date (Nemours previous response: This is because we were utilizing the problem list has our source of truth for the condition end date. Which we found was not accurate. Will use the discharge date as the end date, and discuss with CCHMC.))
1. **provider_id**: Unexpected difference from previous ETL run (the number of providers increased from around 800k providers to 3.2M providers)

## drug_exposure

1. **drug_exposure_end_date**: Implausible Dates - Future (2178)1. **drug_exposure_end_date**: Temporal Outliers (sudden increase around 2009)1. **drug_exposure_end_date**: Implausible Events (32108 records with end date less than start date)
1. **drug_exposure_start_date**: Implausible Dates - Future (2066)1. **drug_exposure_start_date**: Temporal Outliers (sudden increase in 2009 )
1. **lot_number**: Missing Information (100%)
1. **person_id**: Categorical/Entity Outliers (838416618 having over 10k records)
1. **stop_reason**: Missing Information (nearly 50% records have no stop reason (also the most frequent value for stop reason is an empty string (instead of NULL). Is that correct?)
1. **visit_occurrence_id**: Categorical/Entity Outliers (860536989 , 851598189 having 4k drug exposure records)

## measurement

1. **measurement_date**: Significant difference from previous ETL run (the start date in this version is 1950 and in the previous version was 1903. your earlier response was "This are measurements placed from our data abstractors, these are valid measurements, some of these are associated with our seniorcare patients. Others are data entry errors performed by our chart abstractors" So, are these measurements being removed now?)

## observation

1. **observation_date**: Unexpected difference from previous ETL run (start date changed from 1869 to 1931)1. **observation_date**: Temporal Outliers (familiar soike on 2012-01-31)
1. **person_id**: Categorical/Entity Outliers (Number of persons (e.g. 833609868) have observations in the high thousands, but these also have high number of visits �)

## person

1. **ethnicity_source_concept_id**: Unexpected Concept Identifiers (since source data is not encoded in any vocabulary, please use 0 )
1. **gender_source_concept_id**: Unexpected Concept Identifiers (since source data is not encoded in any vocabulary, please use 0 )
1. **provider_id**: Missing Information (100%)

## procedure_occurrence

1. **person_id**: unexpected difference from previous ETL run (In the last ETL run, Person 831074088 has >15K procs, 831690444 has > 10K procs and it was acknowledged as correct by the site (these patients were very sick and were in the hopsital for over a year). However in this current run, the maximum number of procedures for any patient is reduced to 4000?)
1. **procedure_date**: unexpected difference from previous ETL run (earliest start date was 1950 and now it's 2000? Has anything changed since then?)1. **procedure_date**: Temporal Outliers (sudden increase in 2006 )
1. **visit_occurrence_id**: unexpected difference from previous ETL run (In the last ETL run, Visit 893517456 has > 12K procs (and various others have thousands and Nemours's responded with "These are associated with patients that have had extended stays in our facilities. Some over 1.5 years, which means thousands of procedures are associated their visit.". Has something been changed since then? because the maximum number of procedures per visit is now a little over 3K)

## provider

1. **specialty_source_value**: Missing Information (38%)

## visit_occurrence

1. **person_id**: Categorical/Entity Outliers (833609868 having 3500 visits. Is that correct?)
1. **visit_start_date**: unexpected difference from previous ETL run (In the last ETL run the earliest start date was 1869, and now its 1930. HAS something been fixed since then?)


# Low

## drug_exposure

1. **drug_exposure_end_date**: Implausible Dates - Past (1840 etc. )
1. **drug_exposure_start_date**: Implausible Dates - Past (2045, etc. )
1. **provider_id**: Categorical/Entity Outliers ( 398878 , 399062 , 432176  having more than 150k drug exposures)
1. **quantity**: Numerical Outliers (values too high and maximum at 12M)
1. **refills**: Numerical Outliers (values >100 or even upto 2M refills)

## procedure_occurrence

1. **provider_id**: unexpected difference from previous ETL run (the distribution is changed since last ETL run, please clarify)

**Comment by writetoritu** [comment]
We also need a similar tool for generating the feedback for Kevin @murphyke (only for the i2b2 sites: Nemours and Nationwide).  The tool should look for the following conditions and generate a list of all issues (sorted by table name only): 
- Cause == 'i2b2 transform'
- Status == 'solution proposed;

**Comment by bruth** [comment]
Would a flag work to denote the difference in output?

```
dqa-issues -i2b2 -o output.md path/to/results
```

**Comment by writetoritu** [comment]
Yes that would be good. Thanks!
