### ISSUE TITLE
DQA: Need help in populating csv files with "ranks"

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#22]
We would like to automate the issue ranking functionality of the DQA program. (some discussion is here https://github.com/PEDSnet/Data-Quality/issues/72). 

Briefly, here is what we are trying to achieve: (once the csv files are populated by Levon/Ritu),
I/P = data version e.g. pointing to Boston ETL v4 https://github.com/PEDSnet/Data-Quality/tree/master/SecondaryReports/Boston/ETLv4 
Functionality:  In each csv, 
- read the columns table, field, issue code, prevalence , status
- generate a value for the Rank field (Low/Medium/High) based on some simple and straightforward if/else rules (currently, we are manually assigning the ranks but we do have the logic ready)
- update the csv file with those ranks

@bruth please let me know if above can be easily implemented in Go programming language (given the list of rules are likely to be extended in the future)? and you have already implemented any modules that we can re-use for writing this tool? 

Thanks a lot!
Ritu

**Comment by bruth** [comment]
Yes, this would be straightforward to implement. I will add the functionality with the base set of rules you provide and then we can figure out a way to make defining the rules more accessible.

**Comment by bruth** [comment]
@writetoritu When you get a chance, can you document the list of rules that you are manually applying?

**Comment by writetoritu** [comment]
Hi Byron, 

Thanks a lot for looking into this. This will be very useful in improving the DQA workflow. 

Here is an example of a rule: 
(Note: each rule is only applicable for records where Issue_code is not null and Status <> 'persistent')
- If 
  - Table in (care_site, location, provider) && 
  - Field is a source_value (i.e. matches the pattern *_source_value) &&
  - Issue.Code = = 'G2-011' && 
  - Prevalence =='full'
- then 
  - Rank <- "Medium"

In what format should I share the rules with you?

Thanks!
Ritu

**Comment by bruth** [comment]
I think for the time being, you can just describe them like you did above and I will add them into the code directly. In order for them to be supplied or augmented at runtime, I would need to parser and interpret some grammar for these rules. It should be pretty straightforward to implement since the scope is small, but we will push that out unless you need it right away.

**Comment by writetoritu** [comment]
Thanks a lot for this work!

The latest rules are located here: https://github.com/PEDSnet/Data-Quality/tree/master/SecondaryReports/Ranking 
in the csv files
