### ISSUE TITLE
DQA:  proposed enhancement to template generation tool 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#23]
based on some discussion here: https://github.com/PEDSnet/Data-Quality/issues/79 

We would like to have the following new feature in the template generator
- copy all the issues (i.e.all columns from Issue Code - Status) 
  - From: the previous data version for the same site (all issues that are identified as "persistent"  i.e. where Status ="persistent")
  - Into:  the new versions of csv files. 

Also, the templates for "relationship" and "source to concept map" do not need to be generated. 

Thanks a lot and please let me know if you need my help with anything.

**Comment by writetoritu** [comment]
I tried the following command 
./pedsnet-dqa generate-templates --copy-persistent=Colorado/ETLv3/ --root=Colorado/ETLv4 Colorado ETLv4 

It did generate the template files for Colorado ETLv4 - with the following bugs: 
- each persistent issue (from the previous version) is being copied 3 to 4 times , e.g.
  for the care_site tabl (previous report https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Colorado/ETLv3/care_site.csv), 
  - the location_id Consistency issue G4-002 is being copied 3 times, for Consistency, Accuracy and Feasibility 
  - place of service source value, fidelity issue is being copied 4 times for each row of place of service source value

**Comment by writetoritu** [comment]
the template for procedure_occurrence is missing fields "quantity" and "visit occurrence id"

**Comment by writetoritu** [comment]
One more issue - if you look at drug_exposure.csv for Colorado ETL v3, then there are 2 persistent issues for the column drug exposure end date. However, only one got carried forward to the next round (through the  --copy-persistent option)

**Comment by bruth** [comment]
> the template for procedure_occurrence is missing fields "quantity" and "visit occurrence id"

I created a new template for pedsnet 2.0.0 and those fields are present for me.

**Comment by bruth** [comment]
> only one got carried forward to the next round (through the --copy-persistent option)

I see the issue, there are multiple issues listed for the same goal `Consistency`: https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Colorado/ETLv3/drug_exposure.csv#L19-L22 I see the same thing with `drug_exposure_start_date` as well: https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Colorado/ETLv3/drug_exposure.csv#L34-L36

Is this an error or can there be multiple issues for the goal?

**Comment by writetoritu** [comment]
Yes, it is valid to have multiple issues for a goal. They all will have different issue codes.

**Comment by bruth** [comment]
Ok thanks, I will update the code to support that.
