### ISSUE TITLE
Add service layer for data dictionary parser

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#24]

**Comment by bruth** [comment]
I recommend taking a look at the `etl` service: https://github.com/PEDSnet/pedsnet-origins/blob/master/services/etl/main.py

**Comment by l-k-** [comment]
Great, that is what I'm looking at -- thanks for confirming!

**Comment by bruth** [comment]
See #27

**Comment by bruth** [comment]
Implemented in #27
