### ISSUE TITLE
DQA: Create top-level command with subcommands

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#25]
Currently `dqa-files` and `dqa-issues` are two separate programs. With #22 and #23, development would benefit from combining the two source trees. I propose creating a top-level `pedsnet-dqa` program that defines a set of subcommands for the operations required by the DQA team.

@writetoritu Assuming this sounds good to you, do you have recommended command names for `dqa-files` and `dqa-issues`? I was thinking `generate` and `report`?  For example:

```
pedsnet-dqa generate [options]
```

Would correspond to the current `dqa-files` command.

**Comment by writetoritu** [comment]
I like the idea. 
Can we make the command names more descriptive?
- generate-templates
- assign-ranking
- generate-feedback-for-sites
  
  Thanks
  Ritu

**Comment by bruth** [comment]
> Can we make the command names more descriptive?

Yes of course. Whatever makes sense to you.

**Comment by writetoritu** [comment]
Ok then the following names work for me: 
- generate-templates
  - the script to generate templates for secondary reports (currently known as dqa-files) 
  - I will let you decide if you want to include the feature proposed in #23 into the "generate-templates" command or have a separate command for it? 
- assign-rank-to-issues
  - the script to assign ranking to issues - being discussed in #22 
- generate-feedback-for-sites
  - the script to generate the feedback report to sites (in markdown format for GitHub) - currently known as dqa-issues
