### ISSUE TITLE
DQA: Enhance generate-feedback-for-sites script

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#29]
Hi Byron

Based on the feedback received from various sites, we would like to request a couple of enhancements: please see https://github.com/PEDSnet/Data-Quality/issues/114#issuecomment-138957694 

Thanks a lot and please let us know how we can help or if there are any questions. 
Ritu / Levon

**Comment by bruth** [comment]
Thanks for the update and noted. A preview of the new tools should be done by tomorrow!

**Comment by writetoritu** [comment]
finally I was able to run the command 

```
./pedsnet-dqa generate-feedback-for-sites --out=seattle-etlv5.md ./Seattle/ETLv5/
```

however, persistent issues are also being listed in the feedback report - which should not happen. 

Thanks a lot!
