### ISSUE TITLE
Add validate subcommand to DQA tool

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#50]
A few inconsistencies have been found in the secondary report files noted [here](https://github.com/l-k-/tools/blob/b0aba78e1d0b9e58a5fe5f33eea425aa3ad71bba/services/dqa-secondary-reports/report_parser.py#L18-L26).

**Comment by writetoritu** [comment]
Please let me know when the new subcommand ("validate") is ready for testing.

**Comment by bruth** [comment]
This was implemented in 9c5ddec39f8915b4d7d779f2b6ea9e04385402fa
