### ISSUE TITLE
Add ability to specify URL path prefix at deploy time

### ISSUE THREAD

**Issue by gracecodes144** [PEDSnet/tools#54]
I've got the following nginx proxies set up on our internal test server (note that the URLs being passed to are docker-configured container local links). As you can see by visiting https://reslnepdsndev02.research.chop.edu/catalogue and further paths, all are giving 404s of some variety because the apps are not aware they are being server from a path prefix.

**Comment by bruth** [comment]
Can you show a snippet of the nginx config? The client aside, in general the purpose of a proxy is to _not_ have to alter the backend services.

**Comment by gracecodes144** [comment]
Sorry, here it is:

```
    location /catalogue {
        proxy_pass http://catalogue:80;
    }

    location /catalogue/etl {
        proxy_pass http://etlconv:5000;
    }

    location /catalogue/ddl {
        proxy_pass http://sqlalchemy:80;
    }

    location /catalogue/models {
        proxy_pass http://datamodels:8123;
    }

    location /catalogue/datadict {
        proxy_pass http://datadict:5000;
    }

    location /catalogue/dqa {
        proxy_pass http://dqareport:5000;
    }
```

**Comment by gracecodes144** [comment]
Is your comment about the general purpose of proxies intended to motivate a change to the nginx config? There's obviously a lot of proxy configuration settings I am not using that I could investigate.

**Comment by gracecodes144** [comment]
After reading the part of the nginx docs quoted below, I added a `/` to the end of all the proxy_pass URLs and the simpler parts of the services are now working (because nginx has removed the part of the requested URLs that match the location). However, the links and client-side functionality is still not working, as we discussed expecting.

> A request URI is passed to the server as follows:
> 
> If the proxy_pass directive is specified with a URI, then when a request is passed to the server, the part of a normalized request URI matching the location is replaced by a URI specified in the directive:
> 
> ```
> location /name/ {
>     proxy_pass http://127.0.0.1/remote/;
> }
> ```
> 
> If proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client when the original request is processed, or the full normalized request URI is passed when processing the changed URI:
> 
> ```
> location /some/path/ {
>     proxy_pass http://127.0.0.1;
> }
> ```

**Comment by bruth** [comment]
> Is your comment about the general purpose of proxies intended to motivate a change to the nginx config?

Sorry, yes, in a convoluted way.

> the simpler parts of the services are now working

Great!

> However, the links and client-side functionality is still not working, as we discussed expecting.

@l-k- and I are working on it.
