### ISSUE TITLE
enhancing pedsnet-dqa generate-feedback command

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#56]
@bruth 
Currently, the "generate feedback" generates one GH issue per site and contains s list of multiple DQA issues, e.g. https://github.com/PEDSnet/StLouis/issues/25

Based on inputs from @baileych and as a step toward automating the DQA workflow, would it be possible to generate one GH issue per DQA issue, and ...
- automatically post those issues on site's repo with appropriate title
- tag GH them with ranks and table names. 

We haven't agreed upon a final design yet but just curious if that's possible and how much effort would it take?

**Comment by bruth** [comment]
Yes that would not be a problem.

**Comment by bruth** [comment]
For reference here is the API call that would be required: https://developer.github.com/v3/issues/#create-an-issue.

**Comment by writetoritu** [comment]
Thank you @bruth . I am working with @baileych to come up with a good format for these unit issues. A toy example is posted [here](https://github.com/PEDSnet/CHOP/issues/156).

**Comment by bruth** [comment]
Here is a summary after a dicussion with @utidjianl and @writetoritu.
- [ ] Create issues per site for each DQA issue found
- [ ] Label said issues with DQA cycle; [see](https://github.com/PEDSnet/CHOP/issues/156)
- [x] Enhance current summary output of DQA issue report to include links to each issue
- [ ] Create an issue automatically with the summary issue
- [x] Carry over all unresolved issues (not just _persistent_ ones)
- [ ] Add GH link for DQA issues that are carried over

**Comment by writetoritu** [comment]
a minor update: please add "measurement_organism" as a fact table in the generate-feedback command. I will be updating the ranking files accordingly.
