### ISSUE TITLE
pedsnet-dqa generate template

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#60]
minor comments
please remove the following tables
- drug_strength, relationship, and source_to_concept_map

**Comment by bruth** [comment]
I added drug strength, but relationship and source_to_concept_map were already ignored. Do you see them still be generated? Are they being copied over from the previous version using `--copy-persistent`?

**Comment by writetoritu** [comment]
thanks for ignoring drug_strength also. You are right - relationship and source_to_concept_map are already being ignored --- I was looking at the previous reports.
