### ISSUE TITLE
[DQA] Check for summary issue prior to posting duplicate

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#79]

**Comment by writetoritu** [comment]
So, I will be closing individual DQA related issues (on site's repo) as soon as there is consensus between DCC and site on the precise cause (e.g. programming error, unclear conventions, missing in source etc). Does that sound OK to you?

If the issue X re-appears in a subsequent data cycle (except in the case of "Cause: persistent" issues), we will re-open X on GH. Correct? Would it be possible to edit the GH content of X with the latest text in the findings field in secondary report?

**Comment by bruth** [comment]
This was fixed fcf438cb6
