### ISSUE TITLE
[DQA] Request for new subcommand to read from issue log file

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#85]
- _get-auto-identified-issues_ 
- The command will be used right after we run the generate-template command. 
- It will read from the issue log files for a given data version (path specified on the command)
- e.g. there could be an 'issues' folder [here](https://github.com/PEDSnet/CHOP/tree/dqa/DataQualityAssessment/Level1/PEDSnet%20CDM/CHOP%20ETL%20v10). i.e. the R scripts will generate the primary visual reports and and separate issue log. 
- For each entry in the log file for a given table, a new record should be created in the secondary file. 
- A sample log file is attached
  [person_issue.log.txt](https://github.com/PEDSnet/tools/files/427373/person_issue.log.txt)
  (I had to change the extension from .log to .txt to be able to upload on GH)
- If there is a conflict i.e. the same issue code already exists (as a persistent or under review issue from previous cycle), print a conflict warning. (I will prepare conflict resolution rules and share with you later).

**Comment by writetoritu** [comment]
Also, please let me know if you have any feedback on the sample issue log file.

**Comment by bruth** [comment]
In the example log file, the `WARNING: ...` block contains newlines, but is not quoted. This could lead to parsing problems. One suggestion is to simply replace newlines with spaces or commas. 

An alternate suggest is for the log file to be a valid CSV file. This of course would depend on if R has a csv package (I am sure) and if it is easy to integrate in the scripts.

**Comment by bruth** [comment]
Referencing this here from #86 

> all issues logged using the get-auto-identified-issues subcommand should be assigned the 'auto' value for Method.

**Comment by writetoritu** [comment]
Thanks for reviewing the request and providing your feedback on the sample log file. 
Please find some examples of improved log files in the csv format [here](https://github.com/PEDSnet/StLouis/tree/dqa/DataQualityAssessment/Level1/PEDSnet%20CDM/StLouis%20ETL%20v9/issues).

**Comment by bruth** [comment]
The CSV files look great. Is there any significance to the numbers in the first column? I appears to just be the line number without a column name.

**Comment by writetoritu** [comment]
Yes the first column could be ignored ...do you want me to get rid of it or would you be able to ignore it at your end ?

**Comment by bruth** [comment]
I suggest removing since it's not necessary.

**Comment by writetoritu** [comment]
Done - please see [here](https://github.com/PEDSnet/StLouis/tree/dqa/DataQualityAssessment/Level1/PEDSnet%20CDM/StLouis%20ETL%20v9/issues)

**Comment by bruth** [comment]
Looks great, thank you.

**Comment by bruth** [comment]
Implemented in #88. The command is called `merge-issues`.
