### ISSUE TITLE
[DQA] changes to secondary template and logic

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#86]
1. New column to be added to secondary file template: _Method_ 
   - it denotes whether the issue was identified manually or automatically 
   - legal values: 'auto', 'manual'
   - all issues logged using the _get-auto-identified-issues_   subcommand should be assigned the 'auto' value for Method.  
2. Please remove the field 'Reviewer' and 'Site Response'
3. Also, remove the field 'Goal' and we no longer need to generate 4 lines per field. 

Hopefully, the above changes would not break the functionality of other subcommands.
Thanks a lot!

**Comment by writetoritu** [comment]
Also, if an issue is identified as a "Cause:Non-issue", it should not be fed forward to the next version of secondary report.

**Comment by bruth** [comment]
Would you be comfortable if I implemented this as a migration and apply it to all secondary reports to date? This would involve removing the columns from existing files. Or do you want to maintain the existing columns and this only applies to new reports?

**Comment by writetoritu** [comment]
It would be much better if this only applies to new reports. Would that work?

**Comment by bruth** [comment]
Yes that can work.
