### ISSUE TITLE
Implement script to generate DQA template files

### ISSUE THREAD

**Issue by bruth** [PEDSnet/tools#9]
See PEDSnet/Data-Quality#75 for the full discussion. To provide a consistent starting point:

> I need a script that does the following: 
> Input: Model, Model Version, Data Version, Table 
> Output: secondary reports for all tables (with the first seven fields populated) in the correct directory within the DataQuality folder based on the provided data version

**Comment by writetoritu** [comment]
format for data version: PEDSnet-v2-CHOP-ETLv3 
i.e. including model name, model version, site name, and extract version. 

The reports should be created in the appropriate directory, e.g. https://github.com/PEDSnet/Data-Quality/tree/issue-61-sec-reports/SecondaryReports/CHOP/ETLv3 for CHOP's ETL v3
