### ISSUE TITLE
[DQA] ranking rules functionality 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/tools#96]
Hi @bruth 

I ran the ranking tool and the following case wasn't handled: 
https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/CCHMC/ETLv8/provider.csv#L3
although a corresponding rule exists https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Ranking/RuleSet1_Admin.csv#L23

**Comment by bruth** [comment]
The admin rule is defined for BA-001 and the issue in the report has a check code of BA-003.

**Comment by writetoritu** [comment]
sorry please see https://github.com/PEDSnet/Data-Quality/blob/master/SecondaryReports/Ranking/RuleSet1_Admin.csv#L22
